apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - git-repo.yaml
  - helm-release.yaml
  - imagerepository.yaml
  - imagepolicy.yaml
  - imageupdateautomation.yaml
  - dependencies.yaml
  
